### ISSUE TITLE
Template Implementation in .cpp File

### ISSUE THREAD

**Issue by abdumajitovelbek** [abdumajitovelbek/TeamProject#1]
In SupportList.cpp, the SupportList class is a template class, and its implementation is defined in a separate .cpp file. In C++, template definitions must be available in the same translation unit where they are used, typically by including the implementation in the header file (SupportList.h) or ensuring the compiler sees the definitions at compile time.

Problem:
The SupportList<T> class is instantiated in RoadReport.cpp (used as SupportList<int> for supporterIDs).
Since SupportList.cpp is compiled separately, the linker may fail to find the template instantiations for SupportList<int>, leading to undefined reference errors during linking (e.g., undefined reference to SupportList<int>::add(int)).

Evidence:
RoadReport.h includes SupportList.h and uses SupportList<int> supporterIDs.
RoadReport.cpp calls methods like supporterIDs.contains(userID) and supporterIDs.add(userID).
If the compiler doesn’t see the template definitions in SupportList.cpp at the point of instantiation, the linker will fail.
